# Generated by Django 4.2.5 on 2023-11-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_perfilventas_biografia_venta_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
