# Generated by Django 4.2.5 on 2023-11-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_pedido_producto_pedido_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='productos',
            new_name='producto',
        ),
    ]
