# Generated by Django 4.2.5 on 2023-11-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_productos_pedido_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='comentrio',
            new_name='comentario',
        ),
    ]
