# Generated by Django 4.2.5 on 2023-10-30 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='comentarios',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
