# Generated by Django 4.2.5 on 2023-10-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cat_image',
        ),
    ]
