# Generated by Django 4.2.5 on 2023-09-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_crearoom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='creaRoom',
        ),
    ]
