# Generated by Django 4.2.5 on 2023-10-30 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_alter_post_likes_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='likes',
            new_name='Like',
        ),
    ]
