# Generated by Django 4.2.5 on 2023-09-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='perfil.jpg', upload_to=''),
        ),
    ]
