# Generated by Django 4.2.5 on 2023-09-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_profile_image_fondo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_fondo',
        ),
    ]
