# Generated by Django 4.2.5 on 2023-09-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='red_social/media/perfil.jpg', upload_to=''),
        ),
    ]
